---
- block:
  - name: Install vim
    package:
      name: vim
      state: present
    become: yes

  - name: Install git
    package:
      name: git
      state: present
    become: yes

  - name: Install make
    package:
      name: make
      state: present
    become: yes

  - name: Install net-tools
    package:
      name: net-tools
      state: present
    become: yes

  - name: Install wget
    package:
      name: wget
      state: present
    become: yes

