---
- block:
  - name: install vim
    package:
      name: vim
      state: present
    become: yes

  - name: install git
    package:
      name: git
      state: present
    become: yes

  - name: install make
    package:
      name: make
      state: present
    become: yes

  - git: 
      repo: https://github.com/hut/ranger.git
      dest: "{{ installer_dir }}/ranger"

  - name: Build ranger
    make:
      chdir: "{{ installer_dir }}/ranger"
      target: install
    become: yes

  - name: export ranger module install
    shell: export PYTHONPATH=/usr/local/lib/python2.7/site-packages

